window.jQuery = window.$;
//var Velocity = require('./third-party/velocity.min');
require('./third-party/greensock');
require('./third-party/layerslider.transitions');
require('./third-party/layerslider.kreaturamedia.jquery');
require('./third-party/showme.kreaturamedia.jquery');
//require('./third-party/km-ui');
require('./third-party/greensock-text');
//require('./third-party/fastclick');
//require('./third-party/three.min');
var tweenMax = require('./third-party/distorted-buttons/TweenMax.min');
//require('./third-party/bas');
//require('./third-party/OrbitControls-2');
//require('./third-party/segment.min');
//require('./third-party/ease.min');
